### PR TITLE
fix(java): install pyenv in /pyenv instead of /root/.pyenv

### PR DESCRIPTION
**Pull request by chingor13**
This should allow a user to use the docker `--user` flag and still have access to python. Otherwise, it's in `root`'s home directory and inaccessible.

### CODE REVIEW

**Review by BenWhitehead — APPROVED** [review]

**Comment by parthea** [comment]
@chingor13 ok to merge?

**Comment by parthea** [comment]
I'm going to close this PR due to inactivity but please feel free to re-open it.

**Pull request closed without merging**
