### PR TITLE
Use `--depth` flag to `git clone` in Dockerfiles, to save space

### PR DESCRIPTION
**Pull request by Rajpratik71**
optimize the git clone using --depth flag in term of size of clone
and also in term's of time taken to fetch the files and commit history
of whole repository .

More detail can be found at blog
https://www.atlassian.com/git/tutorials/big-repositories

Signed-off-by: Pratik Raj <rajpratik71@gmail.com>

### CODE REVIEW

**Comment by dazuma** [comment]
Please remove the Ruby changes from this PR. (Make Ruby changes in the google-cloud-ruby repo.)

**Comment by Rajpratik71** [comment]
> Please remove the Ruby changes from this PR. (Make Ruby changes in the google-cloud-ruby repo.)

Done there . Can we keep it here also for now as there i didn't see any issue, otherwise i have to again make changes and commit which is waste of time

**Comment by dazuma** [comment]
There's an automated job that rebuilds the images if they are modified, and if the Ruby images are built from here they will clobber the canonical ones that get built from google-cloud-ruby. We need to fix this, but until we do, we need to not make changes to the Ruby images here.

**Comment by Rajpratik71** [comment]
> There's an automated job that rebuilds the images if they are modified, and if the Ruby images are built from here they will clobber the canonical ones that get built from google-cloud-ruby. We need to fix this, but until we do, we need to not make changes to the Ruby images here.

ok got it removing those

**Comment by Rajpratik71** [comment]
> There's an automated job that rebuilds the images if they are modified, and if the Ruby images are built from here they will clobber the canonical ones that get built from google-cloud-ruby. We need to fix this, but until we do, we need to not make changes to the Ruby images here.

So , this applies to all pull in the repo. If that is so , then what is the plan 1. Remove ruby images from here . or 2. To retain ruby images here also

**Comment by dazuma** [comment]
Just do not modify Ruby images.

**Comment by Rajpratik71** [comment]
> Just do not modify Ruby images.

done as requested

**Comment by parthea** [comment]
All, I'm going to close this PR due to inactivity but please feel free to re-open it if it's still needed.

**Pull request closed without merging**
