### PR TITLE
Cleanup Docker installation

### PR DESCRIPTION
**Pull request by gogasca**

### CODE REVIEW

**Comment by kurtisvg** [comment]
This is an alternative to #51? It looks like this is changing `python-base` as well instead of `python-multi`. Is that intentional?

**Comment by gogasca** [comment]
Hi Kurtis, yes, this is intentional found that this other Dockerfile required some cleanup, similar to the one you suggested for the other PR, so I just though we should update this one as well to match  it.

**Comment by gogasca** [comment]
Thanks Kurtis, would you mind merging when you have sometimes?

**Comment by kurtisvg** [comment]
I'd like to wait for @busunkim96 to take a look - the client libraries also use this containers, so I'd like to make sure they are okay with the changes as well

**Comment by busunkim96** [comment]
Looks good to me. You can track the status of the build [here](https://sponge.corp.google.com/invocation?id=581802d8-4f29-46ce-8ba7-d37dd8328665&searchFor). It should be complete in 70-90 minutes.

**Pull request merged**
