### PR TITLE
fix(java): fix debian install for docker

### PR DESCRIPTION
**Pull request by billyjacobson**
using debian instructions for installing docker

### CODE REVIEW

**Comment by chingor13** [comment]
@billyjacobson Looks like the java 10 build failed

**Comment by chingor13** [comment]
Java 9 test is failing the same way as the Java 10 test was

**Comment by billyjacobson** [comment]
@chingor13 got the tests passing finally! Feel free to merge when you get a chance

**Review by chingor13 — APPROVED** [review]

**Pull request merged**
